"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['shotbuf_desktop.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': False}

# from plistlib import Plist
# plist = Plist.fromFile('Info.plist')
# plist.update(dict(
#     LSUIElement=True,
# ))

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)